on:
  workflow_dispatch:
    inputs:
      username:
        description: "phatblat"
        required: true
      reason:
        description: "Why are you running this workflow manually?"
        required: true
        default: "I am running tests before implementing an automated workflow"
